-- 코드를 입력하세요
SELECT A.AUTHOR_ID, A.AUTHOR_NAME, BK.CATEGORY, SUM(BS.SALES * BK.PRICE) AS TOTAL_SALES
FROM BOOK AS BK
JOIN BOOK_SALES AS BS
ON BK.BOOK_ID = BS.BOOK_ID
JOIN AUTHOR AS A
ON BK.AUTHOR_ID = A.AUTHOR_ID
WHERE BS.SALES_DATE LIKE ('2022-01%')
GROUP BY A.AUTHOR_ID, BK.CATEGORY
ORDER BY A.AUTHOR_ID, BK.CATEGORY DESC