# 아이템ID, 아이템명, 희귀도
# 아이템 ID 내림차순

# 아이템이 누군가의 부모ID가 아니어야 된다.

SELECT ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO
WHERE ITEM_ID IN (
    SELECT II.ITEM_ID
    FROM ITEM_TREE AS II
    LEFT OUTER JOIN ITEM_TREE AS IT
    ON II.ITEM_ID = IT.PARENT_ITEM_ID
    WHERE IT.PARENT_ITEM_ID IS NULL
    )
ORDER BY ITEM_ID DESC

