# 입양 간 동물
# 보호 기간이 길었던 2마리
# 아이디, 이름
# 보호 기간 내림차순

SELECT AI.ANIMAL_ID, AI.NAME
FROM ANIMAL_INS AS AI
INNER JOIN ANIMAL_OUTS AS AO
ON AI.ANIMAL_ID = AO.ANIMAL_ID
ORDER BY DATEDIFF(AO.DATETIME, AI.DATETIME) DESC LIMIT 2