# 대장균의 크기를 내림차순 정리
# 상위 0~25 'CRITICAL', 26~50 'HIGH', 51~75 'MEDIUM', 76~100 'LOW'
# ID, COLONY_NAME 출력
# ID 오름차순

SELECT E.ID, CASE 
WHEN E.RANK_SIZE <= ((SELECT COUNT(*) FROM ECOLI_DATA) * 0.25) THEN 'CRITICAL'
WHEN E.RANK_SIZE <= ((SELECT COUNT(*) FROM ECOLI_DATA) * 0.50) THEN 'HIGH'
WHEN E.RANK_SIZE <= ((SELECT COUNT(*) FROM ECOLI_DATA) * 0.75) THEN 'MEDIUM'
ELSE 'LOW' END AS COLONY_NAME
FROM
(
    SELECT ID, RANK() OVER(ORDER BY SIZE_OF_COLONY DESC) AS RANK_SIZE
    FROM ECOLI_DATA 
) AS E
ORDER BY E.ID ASC

