# 중고 거래 게시물 3건 이상 등록
# ID, 닉네임, 전체주소, 전화번호
# 시, 도로명 주소, 상세주소 출력되게
# ID ASC

SELECT UGB.WRITER_ID, UGU.NICKNAME, CONCAT(CONCAT(UGU.CITY, " ", UGU.STREET_ADDRESS1, " ", UGU.STREET_ADDRESS2)) AS '전체주소', 
CONCAT(SUBSTR(UGU.TLNO, 1, 3), "-", SUBSTR(UGU.TLNO, 4, 4), "-", SUBSTR(UGU.TLNO, 8, 4)) AS '전화번호'
FROM USED_GOODS_BOARD UGB
INNER JOIN USED_GOODS_USER UGU ON UGB.WRITER_ID = UGU.USER_ID
GROUP BY UGB.WRITER_ID, UGU.NICKNAME
HAVING COUNT(UGB.WRITER_ID) >= 3
ORDER BY UGU.USER_ID DESC