-- 코드를 입력하세요
SELECT B.USER_ID, B.NICKNAME, CONCAT(B.CITY," ",B.STREET_ADDRESS1," ", B.STREET_ADDRESS2) AS '전체주소', CONCAT(SUBSTR(TLNO, 1,3) ,'-',substr(TLNO, 4,4),'-',substr(TLNO, 8,4)) as '전화번호'
FROM USED_GOODS_BOARD AS A
INNER JOIN USED_GOODS_USER AS B
ON A.WRITER_ID = B.USER_ID
GROUP BY B.USER_ID
HAVING COUNT(B.USER_ID) >= 3
ORDER BY B.USER_ID DESC