# 22-10-16 '대여중', 나머지 대여 가능
#반납 날짜가 22-10-16 ' 대여중'
# 자동차 ID DESC

SELECT CAR_ID,
    MAX(CASE WHEN START_DATE <= '2022-10-16' AND END_DATE >= '2022-10-16' THEN '대여중'
    ELSE '대여 가능' END) AS AVAILABILITY 
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
GROUP BY CAR_ID
ORDER BY CAR_ID DESC