# 아직 입양을 못 간 동물
# 가장 오래 보호소에 있던 동물 3마리 이름, 보호 시작일
# 보호 시작일 순

SELECT AI.NAME, AI.DATETIME
FROM ANIMAL_INS AI 
LEFT JOIN ANIMAL_OUTS AO ON AI.ANIMAL_ID = AO.ANIMAL_ID
WHERE AO.ANIMAL_ID IS NULL
ORDER BY DATETIME ASC LIMIT 3