# 입양 가지 못한 동물 -> ANIMAL_INS에는 있지만 ANIMAL_OUTS에는 없는 것
# 오래 있던 동물 3마리
# 이름, 보호 시작일
# 보호 시작일 오름차순

SELECT AI.NAME, AI.DATETIME
FROM ANIMAL_INS AS AI
LEFT OUTER JOIN ANIMAL_OUTS AS AO
ON AI.ANIMAL_ID = AO.ANIMAL_ID
WHERE AO.ANIMAL_ID IS NULL
ORDER BY AI.DATETIME ASC LIMIT 3