-- 코드를 입력하세요
SELECT APNT.APNT_NO, PT.PT_NAME, PT.PT_NO, APNT.MCDP_CD, DR.DR_NAME, APNT.APNT_YMD
FROM APPOINTMENT AS APNT
INNER JOIN DOCTOR AS DR
ON APNT.MDDR_ID = DR.DR_ID
INNER JOIN PATIENT AS PT
ON APNT.PT_NO = PT.PT_NO
WHERE APNT.APNT_CNCL_YN = 'N' AND APNT.APNT_YMD LIKE '2022-04-13%' AND APNT.MCDP_CD = 'CS'
ORDER BY APNT.APNT_YMD ASC