# 완료된 중고 거래의 총 금액이 70만원 이상
# 회원 ID, 닉네임, 총거래금액
# 총거래금액 오름차순

SELECT UGB.WRITER_ID, UGU.NICKNAME, SUM(UGB.PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD UGB
INNER JOIN USED_GOODS_USER UGU 
ON UGB.WRITER_ID = UGU.USER_ID
WHERE UGB.STATUS = 'DONE'
GROUP BY UGB.WRITER_ID
HAVING SUM(UGB.PRICE) >= 700000
ORDER BY TOTAL_SALES ASC