# 완료된 중고거래
# 총 금액이 70만원 이상
# 회원 ID, 닉네임, 총 거래 금액
# 총 거래 금액 오름차순

SELECT UU.USER_ID, UU.NICKNAME, SUM(UB.PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD AS UB
INNER JOIN USED_GOODS_USER AS UU
ON UB.WRITER_ID = UU.USER_ID
WHERE UB.STATUS = 'DONE'
GROUP BY UU.USER_ID, UU.NICKNAME
HAVING SUM(UB.PRICE) >= 700000
ORDER BY TOTAL_SALES ASC