# ID, 이메일, 이름, 성을 조회
# ID 기준 오름차순

SELECT DISTINCT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS
JOIN SKILLCODES ON SKILLCODES.CODE & DEVELOPERS.SKILL_CODE=SKILLCODES.CODE
WHERE SKILLCODES.NAME IN ('C#','Python')
ORDER BY ID