# 세단인 자동차
# 10월에 대여를 시작한 기록
# 자동차 ID 출력, 중복 X
# ID 내림차순

SELECT DISTINCT(C.CAR_ID)
FROM CAR_RENTAL_COMPANY_CAR AS C
INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS CR
ON C.CAR_ID = CR.CAR_ID
WHERE C.CAR_TYPE = '세단' AND CR.START_DATE LIKE ('2022-10%')
ORDER BY C.CAR_ID DESC