# 물고기 종류 별로 가장 큰 물고기 ID, 물고기 이름, 길이
# 물고기의 ID 오름차순

SELECT FI.ID, FNI.FISH_NAME, FI.LENGTH
FROM FISH_INFO FI
INNER JOIN FISH_NAME_INFO FNI
ON FI.FISH_TYPE = FNI.FISH_TYPE
WHERE FI.ID IN (
    SELECT ID
    FROM FISH_INFO A1
    WHERE LENGTH = (
        SELECT MAX(LENGTH)
        FROM FISH_INFO A2
        WHERE A1.FISH_TYPE = A2.FISH_TYPE
        GROUP BY FISH_TYPE))
ORDER BY FI.ID