# 2022년 1월 카테고리 별 도서 판매량
# 카테고리, 총판매량 출력
# 카테고리명 오름차순

SELECT B.CATEGORY, SUM(BS.SALES)
FROM BOOK AS B
INNER JOIN BOOK_SALES AS BS
ON B.BOOK_ID = BS.BOOK_ID
WHERE BS.SALES_DATE LIKE '2022-01%'
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY ASC
